baseurl = "https://npf.io"
languageCode = "en-us"
title = "npf.io"
theme = "hyde"
copyright = "Nate Finch"

[author]
	name = "Nate Finch"

[permalinks]
	blog = "/:year/:month/:contentbasename/"
	code = "/:contentbasename/"

[taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "code by Nate Finch"
	twitter = "https://twitter.com/natethefinch"
	github = "https://github.com/natefinch"
	gplus = "https://plus.google.com/+NateFinch"
	mainImage = "/moose.svg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

